name: moto_maintanix
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  # add_2_calendar: ^3.0.1
  cupertino_icons: ^1.0.6
  device_calendar: ^4.3.2
  dio: ^5.5.0+1
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1+2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  local_notifier: ^0.1.6
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  open_file: ^3.4.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  timezone: ^0.9.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cars_images/
    - assets/logo/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
