// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/repo/car_table/car_item_model.dart';
import 'models/repo/maint_cost_table/maint_cost_table.dart';
import 'models/repo/maint_reminder_table/maint_reminder_model.dart';
import 'models/repo/maint_table/maint_table.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2644736726534721272),
      name: 'CarItemModel',
      lastPropertyId: const obx_int.IdUid(7, 4485877392755500512),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4386341857696236091),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5384326123355209243),
            name: 'carType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 730701198497241027),
            name: 'brand',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5010530399354534946),
            name: 'model',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3093321621960778265),
            name: 'year',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4761827788490456835),
            name: 'notes',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4485877392755500512),
            name: 'image',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1424666044304327153),
      name: 'MaintCostTable',
      lastPropertyId: const obx_int.IdUid(5, 4740663263791583137),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5440721104729339491),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1838346920051080466),
            name: 'vehicleId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6276726616740733201),
            name: 'maintId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 797930777287238906),
            name: 'cost',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4740663263791583137),
            name: 'part',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 3399358081829213400),
      name: 'MaintReminderModel',
      lastPropertyId: const obx_int.IdUid(7, 3907269406891412037),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3143918936592833977),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6180255291990467718),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2362591484650481106),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4055280715756766388),
            name: 'date',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7410165466750992518),
            name: 'completed',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6423177677198498482),
            name: 'reminderStatus',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3907269406891412037),
            name: 'vehicleId',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 4427088337538947801),
      name: 'MaintTable',
      lastPropertyId: const obx_int.IdUid(8, 1313382227650033690),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4810804903624182236),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6036640739334076623),
            name: 'maintDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 722123457045050887),
            name: 'vehicleId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6850415484799322482),
            name: 'maintType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3845008165725100387),
            name: 'maintDescription',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 914027949301914091),
            name: 'otherNotes',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3475401505067336060),
            name: 'maintStatus',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1313382227650033690),
            name: 'attachedFiles',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(4, 4427088337538947801),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    CarItemModel: obx_int.EntityDefinition<CarItemModel>(
        model: _entities[0],
        toOneRelations: (CarItemModel object) => [],
        toManyRelations: (CarItemModel object) => {},
        getId: (CarItemModel object) => object.id,
        setId: (CarItemModel object, int id) {
          object.id = id;
        },
        objectToFB: (CarItemModel object, fb.Builder fbb) {
          final brandOffset =
              object.brand == null ? null : fbb.writeString(object.brand!);
          final modelOffset =
              object.model == null ? null : fbb.writeString(object.model!);
          final yearOffset =
              object.year == null ? null : fbb.writeString(object.year!);
          final notesOffset =
              object.notes == null ? null : fbb.writeString(object.notes!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.carType);
          fbb.addOffset(2, brandOffset);
          fbb.addOffset(3, modelOffset);
          fbb.addOffset(4, yearOffset);
          fbb.addOffset(5, notesOffset);
          fbb.addOffset(6, imageOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final notesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final carTypeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final brandParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final modelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final yearParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final imageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final object = CarItemModel(
              id: idParam,
              notes: notesParam,
              carType: carTypeParam,
              brand: brandParam,
              model: modelParam,
              year: yearParam,
              image: imageParam);

          return object;
        }),
    MaintCostTable: obx_int.EntityDefinition<MaintCostTable>(
        model: _entities[1],
        toOneRelations: (MaintCostTable object) => [],
        toManyRelations: (MaintCostTable object) => {},
        getId: (MaintCostTable object) => object.id,
        setId: (MaintCostTable object, int id) {
          object.id = id;
        },
        objectToFB: (MaintCostTable object, fb.Builder fbb) {
          final partOffset = fbb.writeString(object.part);
          fbb.startTable(6);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.vehicleId);
          fbb.addInt64(2, object.maintId);
          fbb.addFloat64(3, object.cost);
          fbb.addOffset(4, partOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final maintIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final vehicleIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final costParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final partParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = MaintCostTable(
              id: idParam,
              maintId: maintIdParam,
              vehicleId: vehicleIdParam,
              cost: costParam,
              part: partParam);

          return object;
        }),
    MaintReminderModel: obx_int.EntityDefinition<MaintReminderModel>(
        model: _entities[2],
        toOneRelations: (MaintReminderModel object) => [],
        toManyRelations: (MaintReminderModel object) => {},
        getId: (MaintReminderModel object) => object.id,
        setId: (MaintReminderModel object, int id) {
          object.id = id;
        },
        objectToFB: (MaintReminderModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final dateOffset = fbb.writeString(object.date);
          fbb.startTable(8);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addOffset(3, dateOffset);
          fbb.addBool(4, object.completed);
          fbb.addBool(5, object.reminderStatus);
          fbb.addInt64(6, object.vehicleId);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final dateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final completedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final reminderStatusParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final vehicleIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = MaintReminderModel(
              id: idParam,
              title: titleParam,
              description: descriptionParam,
              date: dateParam,
              completed: completedParam,
              reminderStatus: reminderStatusParam,
              vehicleId: vehicleIdParam);

          return object;
        }),
    MaintTable: obx_int.EntityDefinition<MaintTable>(
        model: _entities[3],
        toOneRelations: (MaintTable object) => [],
        toManyRelations: (MaintTable object) => {},
        getId: (MaintTable object) => object.id,
        setId: (MaintTable object, int id) {
          object.id = id;
        },
        objectToFB: (MaintTable object, fb.Builder fbb) {
          final maintDateOffset = fbb.writeString(object.maintDate);
          final maintTypeOffset = object.maintType == null
              ? null
              : fbb.writeString(object.maintType!);
          final maintDescriptionOffset = object.maintDescription == null
              ? null
              : fbb.writeString(object.maintDescription!);
          final otherNotesOffset = object.otherNotes == null
              ? null
              : fbb.writeString(object.otherNotes!);
          final maintStatusOffset = object.maintStatus == null
              ? null
              : fbb.writeString(object.maintStatus!);
          final attachedFilesOffset = object.attachedFiles == null
              ? null
              : fbb.writeString(object.attachedFiles!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, maintDateOffset);
          fbb.addInt64(2, object.vehicleId);
          fbb.addOffset(3, maintTypeOffset);
          fbb.addOffset(4, maintDescriptionOffset);
          fbb.addOffset(5, otherNotesOffset);
          fbb.addOffset(6, maintStatusOffset);
          fbb.addOffset(7, attachedFilesOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final maintDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final vehicleIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final maintTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final maintDescriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final otherNotesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final maintStatusParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final attachedFilesParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final object = MaintTable(
              id: idParam,
              maintDate: maintDateParam,
              vehicleId: vehicleIdParam,
              maintType: maintTypeParam,
              maintDescription: maintDescriptionParam,
              otherNotes: otherNotesParam,
              maintStatus: maintStatusParam,
              attachedFiles: attachedFilesParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CarItemModel] entity fields to define ObjectBox queries.
class CarItemModel_ {
  /// See [CarItemModel.id].
  static final id =
      obx.QueryIntegerProperty<CarItemModel>(_entities[0].properties[0]);

  /// See [CarItemModel.carType].
  static final carType =
      obx.QueryIntegerProperty<CarItemModel>(_entities[0].properties[1]);

  /// See [CarItemModel.brand].
  static final brand =
      obx.QueryStringProperty<CarItemModel>(_entities[0].properties[2]);

  /// See [CarItemModel.model].
  static final model =
      obx.QueryStringProperty<CarItemModel>(_entities[0].properties[3]);

  /// See [CarItemModel.year].
  static final year =
      obx.QueryStringProperty<CarItemModel>(_entities[0].properties[4]);

  /// See [CarItemModel.notes].
  static final notes =
      obx.QueryStringProperty<CarItemModel>(_entities[0].properties[5]);

  /// See [CarItemModel.image].
  static final image =
      obx.QueryStringProperty<CarItemModel>(_entities[0].properties[6]);
}

/// [MaintCostTable] entity fields to define ObjectBox queries.
class MaintCostTable_ {
  /// See [MaintCostTable.id].
  static final id =
      obx.QueryIntegerProperty<MaintCostTable>(_entities[1].properties[0]);

  /// See [MaintCostTable.vehicleId].
  static final vehicleId =
      obx.QueryIntegerProperty<MaintCostTable>(_entities[1].properties[1]);

  /// See [MaintCostTable.maintId].
  static final maintId =
      obx.QueryIntegerProperty<MaintCostTable>(_entities[1].properties[2]);

  /// See [MaintCostTable.cost].
  static final cost =
      obx.QueryDoubleProperty<MaintCostTable>(_entities[1].properties[3]);

  /// See [MaintCostTable.part].
  static final part =
      obx.QueryStringProperty<MaintCostTable>(_entities[1].properties[4]);
}

/// [MaintReminderModel] entity fields to define ObjectBox queries.
class MaintReminderModel_ {
  /// See [MaintReminderModel.id].
  static final id =
      obx.QueryIntegerProperty<MaintReminderModel>(_entities[2].properties[0]);

  /// See [MaintReminderModel.title].
  static final title =
      obx.QueryStringProperty<MaintReminderModel>(_entities[2].properties[1]);

  /// See [MaintReminderModel.description].
  static final description =
      obx.QueryStringProperty<MaintReminderModel>(_entities[2].properties[2]);

  /// See [MaintReminderModel.date].
  static final date =
      obx.QueryStringProperty<MaintReminderModel>(_entities[2].properties[3]);

  /// See [MaintReminderModel.completed].
  static final completed =
      obx.QueryBooleanProperty<MaintReminderModel>(_entities[2].properties[4]);

  /// See [MaintReminderModel.reminderStatus].
  static final reminderStatus =
      obx.QueryBooleanProperty<MaintReminderModel>(_entities[2].properties[5]);

  /// See [MaintReminderModel.vehicleId].
  static final vehicleId =
      obx.QueryIntegerProperty<MaintReminderModel>(_entities[2].properties[6]);
}

/// [MaintTable] entity fields to define ObjectBox queries.
class MaintTable_ {
  /// See [MaintTable.id].
  static final id =
      obx.QueryIntegerProperty<MaintTable>(_entities[3].properties[0]);

  /// See [MaintTable.maintDate].
  static final maintDate =
      obx.QueryStringProperty<MaintTable>(_entities[3].properties[1]);

  /// See [MaintTable.vehicleId].
  static final vehicleId =
      obx.QueryIntegerProperty<MaintTable>(_entities[3].properties[2]);

  /// See [MaintTable.maintType].
  static final maintType =
      obx.QueryStringProperty<MaintTable>(_entities[3].properties[3]);

  /// See [MaintTable.maintDescription].
  static final maintDescription =
      obx.QueryStringProperty<MaintTable>(_entities[3].properties[4]);

  /// See [MaintTable.otherNotes].
  static final otherNotes =
      obx.QueryStringProperty<MaintTable>(_entities[3].properties[5]);

  /// See [MaintTable.maintStatus].
  static final maintStatus =
      obx.QueryStringProperty<MaintTable>(_entities[3].properties[6]);

  /// See [MaintTable.attachedFiles].
  static final attachedFiles =
      obx.QueryStringProperty<MaintTable>(_entities[3].properties[7]);
}
